#!/usr/bin/env sh
#
# Home Sweet Home - Syncronize dotfiles and configure systems
# Copyright 2014 Guillermo Indalecio Fernandez
#

EXEC=`readlink -f "$0"`
DIR=`dirname "$EXEC"`

die () {
	echo $1
	exit 1
}

do_install () {
	setname=${1:-base}
	filename="$2"
	for file in `find "./home/$setname/" -mindepth 1 -maxdepth 1`
	do
		base=`basename $file`
		local=$HOME/$base
		if [ "$filename" != "" -a "$filename" != "$base" ]
		then
			continue
		fi
		if [ -e "$local" -a '!' -h "$local" ]
		then
			mv "$local" "$local.bak"
		fi
		echo Installing [$setname] $base
		rm -f "$local"
		ln -s "$file" "$local"
	done
}

do_uninstall () {
	setname=${1:-base}
	filename="$2"
	for file in `find "./home/$setname/" -mindepth 1 -maxdepth 1`
	do
		base=`basename $file`
		local=$HOME/$base
		if [ "$filename" != "" -a "$filename" != "$base" ]
		then
			continue
		fi
		if [ -h "$local" ]
		then
			echo Uninstalling [$setname] $base
			rm "$local"
			if [ -e "$local.bak" ]; then
				mv "$local.bak" "$local"
			fi
		fi
	done
}

do_upload () {
	msg=$1
	test -n "$msg" || die "Give me a commit message"
	git commit -a -m "$msg"
	git push
}

do_status () {
	if test -n "$1"; then
		fullfilepath=`readlink "$HOME/$1"` || die "File not found in home"
		git diff "$fullfilepath" | tail -n +5 || die "File not found in repository"
	else
		echo "Home files linked into the repository (modified in bold)"
		echo
		for file in `find ./home/*/ -mindepth 1 -maxdepth 1`
		do
			base=`basename $file`
			local=$HOME/$base
			if [ -h "$local" -a "$file" -ef `readlink "$local"` ]; then
				dir=`dirname "$file"`
				set=`basename "$dir"`
				if test -n "`git status --porcelain $file`"; then
					echo -e "  \033[1m$base\033[0m @ $set"
				else
					echo "  $base @ $set"
				fi
			fi
		done
		echo
	fi
}

do_download () {
	git pull || die "Impossible to download"
}

usage () {
	echo
	echo "Home Sweet Home (hsh)"
	echo
	echo "Usage: hsh <command> [<options>]"
	echo
	echo "Where command is one of:"
	echo
	echo "     install: Link the files in the specified sets into home"
	echo "   uninstall: Try to recover the original files in your home"
	echo "      upload: Push the changes in the files to the repository"
	echo "    download: Update your files with the repository version"
	echo "      status: Get info about installed files and possible changes not commited"
	echo
}

# Dispatch the command entered by the user here
main () {
	cd "$DIR"
	command="$1"
	case "$command" in
		install)
		do_install $2 $3
		;;
		uninstall)
		do_uninstall $2 $3
		;;
		upload)
		do_upload $2
		;;
		download)
		do_download
		;;
		status)
		do_status $2
		;;
		*)
		usage
		;;
	esac
}

(main $@)

